---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 42
          count_threshold: 3
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  stylelint:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- "**/vendor/**/*"
- "**/*.min.css"
- js/vendor/*
