---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 86e657794bdefa94748a3cc3863a1819
    - aae70d598280bb1c4cdabb95c64a30a9
    - 866f47e60dd2327bae9048020bc62c15
    # ... CONFIG CONTENT ...
    config:
      languages:
        javascript:
          mass_threshold: 42
          count_threshold: 3
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  stylelint:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- "**/vendor/**/*"
- "**/*.min.css"
- js/vendor/*
